"""empty message

Revision ID: c5e8c74ca35
Revises: 1bde972783f3
Create Date: 2015-12-12 20:01:37.892293

"""

# revision identifiers, used by Alembic.
revision = 'c5e8c74ca35'
down_revision = '1bde972783f3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'category', ['name'])
    op.create_unique_constraint(None, 'challenge', ['title'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'challenge', type_='unique')
    op.drop_constraint(None, 'category', type_='unique')
    ### end Alembic commands ###
